apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask
  namespace: team1-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: team1-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: team1-namespace
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: anne07/team1-project
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      ServiceAccount: flask

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: team1-namespace
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
     
     
     
     